# Generated by Django 4.2.6 on 2023-12-10 02:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_contacts_notes_alter_contacts_email_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contacts',
            name='notes',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
