# Generated by Django 4.2.6 on 2023-12-10 21:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_alter_contacts_notes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contacts',
            name='time',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
